# Generated by Django 2.0.6 on 2018-09-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.FloatField()),
                ('dob', models.CharField(max_length=250)),
            ],
        ),
    ]
